const DURATION_MS = 3000;
const PROGRESS_DELAY_MS = 50;
const TOTAL_TIMEOUT_MS = DURATION_MS + PROGRESS_DELAY_MS;

export const TOAST = {
  DURATION_MS,
  PROGRESS_DELAY_MS,
  TOTAL_TIMEOUT_MS,
  PROGRESS_WIDTH: {
    START: "100%",
    END: "0%",
  },
};
